import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;

class AIService {
  static const String apiKey = "ENTER YOUR OWN API KEY ";

  Future<String> askAI(String question) async {
    try {
      final response = await http
          .post(
        Uri.parse("https://api.groq.com/openai/v1/chat/completions"),
        headers: {
          "Content-Type": "application/json",
          "Authorization": "Bearer $apiKey",
        },
        body: jsonEncode({
          "model": "llama-3.3-70b-versatile",
          "messages": [
            {
              "role": "system",
              "content": "You are LearnMateAI, a helpful AI tutor for students. Explain concepts clearly and educationally."
            },
            {
              "role": "user",
              "content": question
            }
          ],
        }),
      )
          .timeout(const Duration(seconds: 30));

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        if (data["choices"] != null && data["choices"].isNotEmpty) {
          return data["choices"][0]["message"]["content"];
        }
        return "No response generated by Groq.";
      }

      if (response.statusCode == 429) {
        return "Groq Quota exceeded: The AI is currently busy. Please try again in a moment.";
      }

      return "Groq API Error (${response.statusCode}): Something went wrong.";
    } on TimeoutException {
      return "Request timed out. Please check your internet connection.";
    } catch (e) {
      return "Error: $e";
    }
  }
}
