// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHnsRmSyDPXxSIe0Q4qlRiEQI5BJqmkx8',
    appId: '1:981625511495:web:93df956cb44102f8485b62',
    messagingSenderId: '981625511495',
    projectId: 'learnmateai-a1d09',
    authDomain: 'learnmateai-a1d09.firebaseapp.com',
    storageBucket: 'learnmateai-a1d09.firebasestorage.app',
    measurementId: 'G-7WMW7QDHST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA47TG8emmTxP8F-uzFlNTXgnR6Z18iFso',
    appId: '1:981625511495:android:a8d4e7ee0923814b485b62',
    messagingSenderId: '981625511495',
    projectId: 'learnmateai-a1d09',
    storageBucket: 'learnmateai-a1d09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbruh0hqpbsju_QjFfgKXDudijjliiDko',
    appId: '1:981625511495:ios:31a6d896c050d92a485b62',
    messagingSenderId: '981625511495',
    projectId: 'learnmateai-a1d09',
    storageBucket: 'learnmateai-a1d09.firebasestorage.app',
    iosBundleId: 'com.techiguru.learnmateai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbruh0hqpbsju_QjFfgKXDudijjliiDko',
    appId: '1:981625511495:ios:31a6d896c050d92a485b62',
    messagingSenderId: '981625511495',
    projectId: 'learnmateai-a1d09',
    storageBucket: 'learnmateai-a1d09.firebasestorage.app',
    iosBundleId: 'com.techiguru.learnmateai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHnsRmSyDPXxSIe0Q4qlRiEQI5BJqmkx8',
    appId: '1:981625511495:web:d267bae94f72c74d485b62',
    messagingSenderId: '981625511495',
    projectId: 'learnmateai-a1d09',
    authDomain: 'learnmateai-a1d09.firebaseapp.com',
    storageBucket: 'learnmateai-a1d09.firebasestorage.app',
    measurementId: 'G-0DWYKDQR3M',
  );
}
